### ISSUE TITLE
missing: tests

### ISSUE THREAD

**Issue by juliuste** [juliuste/westminster-svg#1]
It would be nice to have some really basic tests (preferably using `tape`).

**Comment by grigori-gru** [comment]
Hello! May I help you with this?

**Comment by riktimmondal** [comment]
Can you describe what kind of test do we need?

**Comment by juliuste** [comment]
Since I probably won't make any changes to the actual "math" behind this project, tests could just compare the live svg output to another svg "snapshot" we take now. Tests would then break if something changed compared to now, which would be sufficient since everything works fine at the moment. 
I know that this could break as soon as we change anything about the algorithm itself (e. g. adjusting the spacing between the seats), but avoiding this would probably make testing way more complicated.
If you have any other proposals though, feel free to present them, since the above "strategy" is definitely not optimal 😄

**Comment by juliuste** [comment]
By the way, whoever likes to do this, maybe see juliuste/parliament-svg#6 as well (:
